trigger:
  - main

pool: local-agent

resources:
  - repo: self

variables:
  - group: "CICD"
  - name: app_var
    value: $[variables.appVariable]
    
parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "public-api"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool: local-agent 

        steps:
          - script: |
              echo "var=$(app_var)"

          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: ${{ parameters.imageName }}
              command: build
              dockerfile: "**/qa.dockerfile"
              tags: ${{ parameters.tag }}
              arguments: "--build-arg APP_ENV=$(app_var)"
